### ISSUE TITLE
the opposite function: share to open a file

### ISSUE THREAD

**Issue by zzh1996** [haruue/OpenWithX#1]
I want the opposite function, too.
For example, when I preview a photo in telegram, there is a 'share' button.
But some apps (like photoshop touch) only accept opening files but not sharing.
I hope I can share the photo to OpenWithX and then OpenWithX pops up an app list to open the file with.
If the shared content is not a file, I think you can save it to a temp file and then open the temp file.

**Comment by haruue** [comment]
Yes I will implement it. In fact, this feature is in design but I am just busy in another private repo recently. 


Thank you for your advice.
